### ISSUE TITLE
Architectural responsibility layers

### ISSUE THREAD

**Issue by vladkampov** [roman-melnishin/docker-react-app#1]
Hello @roman-melnishin, thanks for the task completion, I am kindly appreciate that. 
I am Vlad, Front-end developer of 90POE. 

Looking into your code I've got several topics to discuss. Let's make this through github issues.

Looking into the app structure and responsibility parts of the code I think something could be improved, I bet there was lack of time to do it perfectly. Wouldn't it be so rude to ask you look again into your code, spent a bit more time and maybe you'll find some parts for improvement?

Thanks in advance :)

**Comment by roman-melnishin** [comment]
Hi! Thanks for remarks. All changes have been applied at https://github.com/roman-melnishin/docker-react-app/commit/7ad0ad44b84e0e986a56f883bc7283f22659d7dc
